### ISSUE TITLE
FT_Init_FreeType() call causes segfaults on 32-bit Linux

### ISSUE THREAD

**Issue by sotaroikeda** [servo/rust-freetype#50]
FT_Init_FreeType() call  in WebRender caused segfaults on 32-bit Linux. I actually tested on 32bit Ubuntu16.04. From the symptom, stack seems to be broken by FT_Init_FreeType() call.

There seems to be inconsistency about how to handle return value between native and rust.

See servo/webrender#2511

**Comment by sotaroikeda** [comment]
FT_Error seems to trigger the segfaults. When it is defined simply as ::std::os::raw::c_int, the problem did not happen. 

-----------------------------------------------------

/// A wrapper over v so we can add convenience methods on it.
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub struct FT_Error(pub ::std::os::raw::c_int);

impl FT_Error {
    #[inline]
    pub fn succeeded(&self) -> bool {
        self.0 == freetype::FT_Err_Ok as ::std::os::raw::c_int
    }
}

**Comment by sotaroikeda** [comment]
Following sample code caused the segfaults.

`extern crate freetype;

use std::ptr;
use freetype::freetype::{FT_Library, FT_Init_FreeType};

fn main() {
  let mut lib: FT_Library = ptr::null_mut();

  unsafe {
      FT_Init_FreeType(&mut lib)
  };
}`

**Comment by sotaroikeda** [comment]
By default, FT_Init_FreeType() with llvm-ir was like the following 
>   call void @FT_Init_FreeType(%"freetype::FT_Error"* noalias nocapture sret dereferenceable(4) %_2, %"freetype::freetype::FT_LibraryRec_"** %lib),

When FT_Error was changed to ::std::os::raw::c_int, FT_Init_FreeType() with llvm-ir was like the following
>    %1 = call i32 @FT_Init_FreeType(%"freetype::freetype::FT_LibraryRec_"** %lib),

The difference seems to related to the segfaults.

**Comment by sotaroikeda** [comment]
It looks similar to rust-lang/rust#39394

@emilio , what is the good way to address  the problem?

**Comment by SimonSapin** [comment]
One solution is to add [`#[repr(transparent)]`](https://github.com/rust-lang/rust/issues/43036) to the type, but that’s not stable yet. Another is to replace the struct with a `type` alias, and "downgrade" the convenience methods to free functions.

**Comment by sotaroikeda** [comment]
#[repr(transparent)] is ideal, but we could not use it with stable channel :(

**Comment by sotaroikeda** [comment]
Fixed.
